spring.application.name=crud-api-chakray

app.security.aes-secret-key-hex=${AES_SECRET_KEY_HEX:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
